services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mcp_pro_user
      POSTGRES_PASSWORD: mcp_pro_password
      POSTGRES_DB: mcp_pro_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/backend/db/00_create_tables.sql:/docker-entrypoint-initdb.d/00_create_tables.sql # Added this line
      - ./packages/backend/db/seed_mcp_marketplace_server.sql:/docker-entrypoint-initdb.d/01_seed_mcp_marketplace_server.sql
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: production
    restart: always
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://mcp_pro_user:mcp_pro_password@postgres:5432/mcp_pro_db?schema=public
      NODE_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: mcp_pro_user
      POSTGRES_PASSWORD: mcp_pro_password
      POSTGRES_DB: mcp_pro_db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./packages/frontend/.env
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001 # URL of the backend
      NODE_ENV: development # Change to production for actual deployments
      # Add other frontend environment variables here
    volumes:
      - ./packages/frontend:/usr/src/app/packages/frontend
      - ./packages/shared-types:/usr/src/app/packages/shared-types
      # Exclude node_modules from volume mount to avoid conflicts
      - /usr/src/app/node_modules
    depends_on:
      - backend
    command: npm run dev --workspace=frontend

volumes:
  postgres_data:
